arapp/urls.py
from django.urls import path

from . import views
from .views import TopView, MotherDayView

app_name = 'arapp'
urlpatterns = [
  path('', TopView.as_view(), name='top'),
  path('forMom/', MotherDayView.as_view(), name='mom'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('arapp.urls')),
]

arapp/models.py
from django.db import models

# Create your models here.

arapp/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.
class TopView(View):
  def get(self, request, *args, **kwargs):
    return render(request, 'arapp/top.html')

class MotherDayView(View):
  def get(self, request, *args, **kwargs):
    return render(request, 'arapp/mom.html')

top = TopView.as_view()
mother = MotherDayView.as_view()

templates/arapp/mom.html
{% extends 'base_ar.html' %}

{% load static %}

{% block extra_css %}
  <style type="text/css">
    #target1 {
      height: 120px;
      width: 120px;
      z-index: -50;
      background-color: #FFF;
    }
  </style>
{% endblock %}

{% block extra_js %}
{% endblock %}

{% block target%}
  <div id="target1" class="target">
    <div>
      <h3>A-Frame</h3>
      <p>A-Frame Sample</p>
      <p class="detail">320px x 200px</p>
    </div>
  </div>
{% endblock %}

{% block content %}
  <a-assets>
    <a-asset-item id="rose-mtl" src="{% static  'model_obj/rose/rose.mtl' %}"></a-asset-item>
    <a-asset-item id="rose-obj" src="{% static  'model_obj/rose/rose.obj' %}"></a-asset-item>
  </a-assets>

  <!-- ④ マーカーを追加 ここから -->
  <a-marker type="pattern" url="{% static 'marker/pattern-marker.patt' %}">
    <a-entity position="0 2.25 -15" size="5" particle-system="preset: rain"></a-entity>
    <a-text value="Happy Mother's Day!!" rotation="-90 0 0" position="0 1.3 0" align="center"></a-text>
    <a-obj-model id="rose" src="#rose-obj" mtl="#rose-mtl" position="0 0 0" scale="0.03 0.03 0.03" rotation="-60 0 0" ></a-obj-model>
  </a-marker>

  <a-marker preset="hiro">
    <!-- ⑤ オブジェクトの追加 -->
    <a-text value="Happy Mother's Day!!" rotation="-90 0 0" position="0 1.3 0" align="center"></a-text>
    <a-plane width="1" height="1" rotation="-90 0 0" material="shader:html; target: #target1"></a-plane>
  </a-marker>
{% endblock %}

templates/arapp/top.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <div class="ui two column grid">
    <div class="column">
      <div class="ui segment">
        <a href="{% url 'arapp:mom' %}" class="ui xlarge image">
          <img src="{% static 'images/mother_day.jpg' %}">
        </a>
      </div>
    </div>
    <div class="column">
      <div class="ui segment">
        <a href="#" class="ui xlarge image">
          <img src="{% static 'images/coming_soon.jpg' %}">
        </a>
      </div>
    </div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block page_title %}{% endblock %} thx2fam</title>

  {# --- css --- #}
  <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
  <style type="text/css">
    body {
      background-color: #dadada;
    }
  </style>
  {% block extra_css %}{% endblock %}
</head>
<body>
  <div class="ui stackable menu">
    <div class="item">
      <a href="{% url 'arapp:top' %}">THX2FAM</a>
    </div>
  </div>
  <div class="ui container">
    {% block content %}{% endblock %}
  </div>
  {# --- js --- #}
  <script src="{% static 'js/jquery-3.4.0.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'js/semantic.min.js' %}"></script>
  {% block extra_js %}{% endblock %}
</body>
</html>

templates/base_ar.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>thx2fam</title>
    <script src="https://aframe.io/releases/0.8.0/aframe.min.js"></script>
    <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.6.2/aframe/build/aframe-ar.js"></script>
    <script src="https://unpkg.com/aframe-html-shader@0.2.0/dist/aframe-html-shader.min.js"></script>
    <script src="http://html2canvas.hertzen.com/dist/html2canvas.min.js"></script>
    <script src="https://unpkg.com/aframe-particle-system-component@1.0.x/dist/aframe-particle-system-component.min.js"></script> 
    <!-- ① A-Frame を読み込む -->
    <!-- <script src="https://aframe.io/releases/0.6.1/aframe.min.js"></script> -->
    <!-- ② AR.js を読み込む -->
    <!-- <script src="https://cdn.rawgit.com/jeromeetienne/AR.js/1.5.0/aframe/build/aframe-ar.js"></script> -->
    <!-- <script src="{% static 'js/aframe-html-shader.min.js' %}"></script> -->
    <!-- <script src="{% static 'js/html2canvas.min.js' %}"></script> -->
    {% block extra_css %}{% endblock %}

  </head>
  <body style="margin: 0; overflow: hidden;">
    {% block target%}
    {% endblock%}
    <!-- ③ シーンを追加 -->
    <a-scene embedded arjs="debugUIEnabled:false;" vr-mode-ui="enabled: false">
      {% block content %}
      {% endblock %}
      <!-- ⑥ カメラを追加 -->
      <a-entity camera></a-entity>
    </a-scene>
    {% block extra_js %}{% endblock %}
  </body>
</html>